services:
  - type: web
    name: nse-screener-proxy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "nse_app.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
